.PHONY: install build all run ci

all: build

install:
	yarn install

build:
	npm run build

lint:
	npm run lint

format:
	npm run format

ci:
	npm run ci

run:
	npm run start

run-debug:
	npm run dev
