.PHONY: install build lint format test ci run run-debug all

install:
	yarn install
	yarn global add react-scripts

build:
	npm run build

lint:
	npm run lint

format:
	npm run format

test:
	npm run test

ci:
	npm run ci

run:
	npm run start

run-debug:
	npm run dev
