name: frontend
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12'
      id: go
    - name: Check out code
      uses: actions/checkout@v2
    - name: Get deps
      run: make install
      working-directory: frontend
    - name: Lint
      run: make lint
      working-directory: frontend
    - name: Build
      run: make build
      working-directory: frontend
    - name: Test
      run: make test
      working-directory: frontend
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        registry: docker.pedanticorderliness.com
        username: ${{ secrets.DOCKER_REG_USER }}
        password: ${{ secrets.DOCKER_REG_PASS }}
        repository: club-frontend
        tags: ${{ github.sha }},latest
        path: frontend
    - name: Deploy
      run: |
        curl --fail -X PUT -H "X-Access-Token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}" "https://actions.pedanticorderliness.com/deploy?repo=$GITHUB_REPOSITORY/frontend&tag=$GITHUB_SHA"

