// Code generated by counterfeiter. DO NOT EDIT.
package signalingfakes

import (
	"sync"

	"github.com/ryanrolds/club/pkg/signaling"
)

type FakeReceiverNode struct {
	GetParentStub        func() signaling.ReceiverNode
	getParentMutex       sync.RWMutex
	getParentArgsForCall []struct {
	}
	getParentReturns struct {
		result1 signaling.ReceiverNode
	}
	getParentReturnsOnCall map[int]struct {
		result1 signaling.ReceiverNode
	}
	IDStub        func() signaling.NodeID
	iDMutex       sync.RWMutex
	iDArgsForCall []struct {
	}
	iDReturns struct {
		result1 signaling.NodeID
	}
	iDReturnsOnCall map[int]struct {
		result1 signaling.NodeID
	}
	ReceiveStub        func(signaling.Message)
	receiveMutex       sync.RWMutex
	receiveArgsForCall []struct {
		arg1 signaling.Message
	}
	SetParentStub        func(signaling.ReceiverNode)
	setParentMutex       sync.RWMutex
	setParentArgsForCall []struct {
		arg1 signaling.ReceiverNode
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeReceiverNode) GetParent() signaling.ReceiverNode {
	fake.getParentMutex.Lock()
	ret, specificReturn := fake.getParentReturnsOnCall[len(fake.getParentArgsForCall)]
	fake.getParentArgsForCall = append(fake.getParentArgsForCall, struct {
	}{})
	fake.recordInvocation("GetParent", []interface{}{})
	fake.getParentMutex.Unlock()
	if fake.GetParentStub != nil {
		return fake.GetParentStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.getParentReturns
	return fakeReturns.result1
}

func (fake *FakeReceiverNode) GetParentCallCount() int {
	fake.getParentMutex.RLock()
	defer fake.getParentMutex.RUnlock()
	return len(fake.getParentArgsForCall)
}

func (fake *FakeReceiverNode) GetParentCalls(stub func() signaling.ReceiverNode) {
	fake.getParentMutex.Lock()
	defer fake.getParentMutex.Unlock()
	fake.GetParentStub = stub
}

func (fake *FakeReceiverNode) GetParentReturns(result1 signaling.ReceiverNode) {
	fake.getParentMutex.Lock()
	defer fake.getParentMutex.Unlock()
	fake.GetParentStub = nil
	fake.getParentReturns = struct {
		result1 signaling.ReceiverNode
	}{result1}
}

func (fake *FakeReceiverNode) GetParentReturnsOnCall(i int, result1 signaling.ReceiverNode) {
	fake.getParentMutex.Lock()
	defer fake.getParentMutex.Unlock()
	fake.GetParentStub = nil
	if fake.getParentReturnsOnCall == nil {
		fake.getParentReturnsOnCall = make(map[int]struct {
			result1 signaling.ReceiverNode
		})
	}
	fake.getParentReturnsOnCall[i] = struct {
		result1 signaling.ReceiverNode
	}{result1}
}

func (fake *FakeReceiverNode) ID() signaling.NodeID {
	fake.iDMutex.Lock()
	ret, specificReturn := fake.iDReturnsOnCall[len(fake.iDArgsForCall)]
	fake.iDArgsForCall = append(fake.iDArgsForCall, struct {
	}{})
	fake.recordInvocation("ID", []interface{}{})
	fake.iDMutex.Unlock()
	if fake.IDStub != nil {
		return fake.IDStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.iDReturns
	return fakeReturns.result1
}

func (fake *FakeReceiverNode) IDCallCount() int {
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	return len(fake.iDArgsForCall)
}

func (fake *FakeReceiverNode) IDCalls(stub func() signaling.NodeID) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = stub
}

func (fake *FakeReceiverNode) IDReturns(result1 signaling.NodeID) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	fake.iDReturns = struct {
		result1 signaling.NodeID
	}{result1}
}

func (fake *FakeReceiverNode) IDReturnsOnCall(i int, result1 signaling.NodeID) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	if fake.iDReturnsOnCall == nil {
		fake.iDReturnsOnCall = make(map[int]struct {
			result1 signaling.NodeID
		})
	}
	fake.iDReturnsOnCall[i] = struct {
		result1 signaling.NodeID
	}{result1}
}

func (fake *FakeReceiverNode) Receive(arg1 signaling.Message) {
	fake.receiveMutex.Lock()
	fake.receiveArgsForCall = append(fake.receiveArgsForCall, struct {
		arg1 signaling.Message
	}{arg1})
	fake.recordInvocation("Receive", []interface{}{arg1})
	fake.receiveMutex.Unlock()
	if fake.ReceiveStub != nil {
		fake.ReceiveStub(arg1)
	}
}

func (fake *FakeReceiverNode) ReceiveCallCount() int {
	fake.receiveMutex.RLock()
	defer fake.receiveMutex.RUnlock()
	return len(fake.receiveArgsForCall)
}

func (fake *FakeReceiverNode) ReceiveCalls(stub func(signaling.Message)) {
	fake.receiveMutex.Lock()
	defer fake.receiveMutex.Unlock()
	fake.ReceiveStub = stub
}

func (fake *FakeReceiverNode) ReceiveArgsForCall(i int) signaling.Message {
	fake.receiveMutex.RLock()
	defer fake.receiveMutex.RUnlock()
	argsForCall := fake.receiveArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeReceiverNode) SetParent(arg1 signaling.ReceiverNode) {
	fake.setParentMutex.Lock()
	fake.setParentArgsForCall = append(fake.setParentArgsForCall, struct {
		arg1 signaling.ReceiverNode
	}{arg1})
	fake.recordInvocation("SetParent", []interface{}{arg1})
	fake.setParentMutex.Unlock()
	if fake.SetParentStub != nil {
		fake.SetParentStub(arg1)
	}
}

func (fake *FakeReceiverNode) SetParentCallCount() int {
	fake.setParentMutex.RLock()
	defer fake.setParentMutex.RUnlock()
	return len(fake.setParentArgsForCall)
}

func (fake *FakeReceiverNode) SetParentCalls(stub func(signaling.ReceiverNode)) {
	fake.setParentMutex.Lock()
	defer fake.setParentMutex.Unlock()
	fake.SetParentStub = stub
}

func (fake *FakeReceiverNode) SetParentArgsForCall(i int) signaling.ReceiverNode {
	fake.setParentMutex.RLock()
	defer fake.setParentMutex.RUnlock()
	argsForCall := fake.setParentArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeReceiverNode) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getParentMutex.RLock()
	defer fake.getParentMutex.RUnlock()
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	fake.receiveMutex.RLock()
	defer fake.receiveMutex.RUnlock()
	fake.setParentMutex.RLock()
	defer fake.setParentMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeReceiverNode) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ signaling.ReceiverNode = new(FakeReceiverNode)
